- src/js/JS.aut.far.functions.base.min.js
A alteração foi realizada na linha 242 aonde está 220 antes tinha o valor de 194 fazendo com que o botão ficasse pela metade.
> B2C-1546 - Adiciona script da MZ para corrigir abertura do carrinho

- dev/js/JS.aut.far.functions.base.min.dev.js
- dev/js/galeria-imagem-video.dev.js
> B2C-1837 -Criando arquivo para teste da poc

- src/css/whatsapp-icon.css
> B2C-1857 - corrigindo seletor img e acertando forma de ocultar o ícone da zendesk

- src/js/whatsapp-icon.js
Criando JS para ajustar margin-bottom do ícone quando houver barra fixa inferior (página do produto no mobile)
> B2C-1857 - criando JS para ajustar margin-bottom do ícone quando houver barra fixa inferior (página do produto no mobile)

- src/css/whatsapp-icon.css
Corrigindo problema de sobreposição dos ícones em telas menores (ambiente de teste)
> B2C-1887 - Corrigindo problema de sobreposição dos ícones em telas menores (ambiente de teste)

- arquivos/css/whatsapp-icon.css
Corrigindo problema de sobreposição dos ícones em telas menores (produção)
> B2C-1887 - Corrigindo problema de sobreposição dos ícones em telas menores (produção)

- hml/consulta-agendamento.js
> B2C-1863 - Aplicando em ambiente de HML

- src/js/policies/checkout.js
- Ajustando política caso geral Pernambuco
- Adicionando faixa de CEP faltante no caso geral de SP
> B2C-1885 - Ajustando política caso geral Pernambuco e adicionando faixa de CEP faltante no caso geral de SP

- src/js/policies/checkout.js
Commit inicial. Alteração geral da lógica e ajustes nas faixas de CEP
> B2C-1885_v2 - Commit inicial. Alteração geral da lógica e ajustes nas faixas de CEP

- src/js/policies/checkout.js
Corrigindo nome da política 15 (PE) no caso geral de MG23 para RC01
> B2C-1885_v2 - Corrigindo nome da política 15 (PE) no caso geral de MG23 para RC01

- src/js/policies/header.js
Corrigindo sequencia de execução do redirecionamento da página para aplicação de política
> B2C-1892 - Corrigindo sequencia de execução do redirecionamento da página para aplicação de política

- src/js/policies/header.js
Alterando política de SP em home e página do produto de 29 para 26
> B2C-1885_v2 - Alterando política de SP em home e página do produto de 29 para 26

- hml/consulta-agendamento.js
- hml/detalhe-produto.js
- hml/legacy-MZ-CBKY.js
Incluindo política na chamada de api de simulação de frete da VTEX
> B2C-1885_v2 - Incluindo política na chamada de api de simulação de frete da VTEX

- hml/legacy-MZ-CBKY.js
Excluindo caractere no código minificado legado que estava causando problema de formatação no rodapé
> B2C-1885_v2 - excluindo caractere no código minificado legado que estava causando problema de formatação no rodapé

- src/js/whatsapp-icon.js
Registrando evento do google analytics no script
> B2C-1908 - Registrando evento do google analytics no script

- src/css/detalhe-produto.css
Ajustando z-index de compre junto e nav-container
> B2C-1907 - Ajustando z-index de compre junto e nav-container

- src/css/home.css
- src/css/ratings.css
- src/css/theme.css
Ocultando elementos de imagem dos cards de avaliações na Home e Página do Produto
> B2C-1909 - Ocultando elementos de imagem dos cards de avaliações na Home e Página do Produto

- arquivos/css/home.css
- arquivos/css/ratings.css
> B2C-1909 - Aplicando em produção

- src/css/legacy/CSS.aut.far.qd-bootstrap-common.css
Criando cópia do arquivo legado e já com a alteração de cores solicitada
> B2C-1890 - criando cópia do arquivo legado e já com a alteração de cores solicitada

- src/css/filtro-veiculos.dev.css
- src/css/whatsapp-icon.css
- src/js/smart-select.dev.js
Corrigindo alinhamento do botão 'Filtrar Resultado' e
Rolando a visão da tela direto para os resultados de busa
> B2C-1889 - melhorando apresentacao do resultado de busca em dispositivos móveis

- src/js/checkout.js
- src/js/header.js
Duplicando arquivos para teste e otimizando criação do cookie VTEXSC
> B2C-1926 - duplicando arquivos para teste e otimizando criação do cookie VTEXSC

- src/js/detalhe-produto-2.js
Copiando arquivo detalhe-produto para pasta src/ para ambiente de teste
> B2C-1902 - copiando arquivo detalhe-produto para pasta src/ para ambiente de teste

- src/css/consulta-agendamento.dev.css
- src/js/consulta-agendamento.js
Exibindo cards de lojas sem horário disponível, desde que haja ao menos uma outr loja com horário disponível na mesma data.
E alterando estilo desses cards, deixando menos opaco.
> B2C-1903 - exibindo cards de lojas sem horário disponível e alterando estilo desses cards

- arquivos/css/legacy/CSS.aut.far.qd-bootstrap-common.css
- src/css/legacy/CSS.aut.far.qd-bootstrap-common.css
Alterando dominios das URLs de imagens de background de 'devautoglass.vteximg.com.br' para 'www.autoglassonline.com.br'
> B2C-1934 - Alterando dominios das URLs de imagens de background de 'devautoglass.vteximg.com.br' para 'www.autoglassonline.com.br'

- src/css/servicos.css
Criando arquivos CSS para estilização da landing page de serviços já com estilização do banner
> B2C-1948 - Criando arquivos CSS para estilização da landing page de serviços já com estilização do banner

- src/css/servicos/form-servicos.css
- src/styles/global/style.css
A fim de melhorar a responsividade utilizasse a unidade de medida rem.
> B2C-1948 - Alterado unidade de medida para responsividade

- src/css/servicos/form-servicos.css
Removendo fonte bold dos labels do formulário
> B2C-1948 - Removendo fonte bold dos labels do formulário

- src/css/servicos/form-servicos.css
- src/css/servicos/servicos.css
- src/styles/global/style.css
…textoAdicionando cursor pointer nos radio button e compactando texto
> B2C-1948 - Adicionando cursor pointer nos radio button e compactando texto

- src/css/legacy/CSS.aut.far.qd-bootstrap-common.css
Adicionado ancora (link) de serviços no rodapé
> B2C-1948 - Adicionado ancora (link) de serviços no rodapé

- src/css/legacy/CSS.aut.far.atendimento.css
Hospedando CDN legado e implementando links de serviço.
> B2C-1948 - Hospedando CDN legado e implementando melhoria

- src/js/checkout.js
Verificando e corrigindo inconsistencia de selectedDeliveryChannel no orderform quando é selecionado modo pickup-in-point
> B2C-1975 - verificando e corrigindo inconsistencia de selectedDeliveryChannel no orderform quando é selecionado modo pickup-in-point

- src/css/servicos/form-servicos.css
- src/css/servicos/servicos.css
- src/css/servicos/vantagens/pintura-automotiva.css
- src/styles/global/style.css
Ajustando os valores realtivo a 'rem' devido a conflito de estilização com o sidebar
> B2C-1948 - Ajustando os valores realtivo a 'rem' devido a conflito de estilização com o sidebar

- src/css/servicos/servicos.css
Realocação do formulário na pagina.
> B2C-1948 - Realocação do formulário na pagina.

- arquivos/css/servicos/servicos.css
(Produção) Realocação do formulário na pagina.
> B2C-1948 - (Produção) Realocação do formulário na pagina.

- src/css/servicos/form-servicos.css
- src/js/form-servicos.js
Ajustes no botão ancora - faça seu orçamento.
> B2C-1948 - Ajustes no botão ancora - faça seu orçamento.

- src/css/servicos/form-servicos.css
- src/js/form-servicos.js
Reverts Autoglass-CDN/Autoglass-CDN.github.io#648
> Revert "B2C-1948 - Ajustes no botão ancora - faça seu orçamento."

- src/css/servicos/form-servicos.css
> B2C-1948 - Ajustes css Anchor-form

- arquivos/css/servicos/form-servicos.css
- arquivos/css/servicos/servicos.css
- arquivos/js/form-servicos.js
> B2C-1948 - Aplicando em produção

- src/css/topo.css
Ajuste link blog no header mobile
> B2C-1994 Ajuste link blog no header mobile

- arquivos/css/topo.css
Aplicando ajuste no link para o blog em produção.
> B2C-1994 Aplicando ajuste no link para o blog em produção.

- _BackupCMS/Checkout/Desenvolvimento/checkout6-custom.js
Corrigindo seletor do botão de opção de pagamento na loja
> B2C-2000 - Registrando alteração em checkout6-custom.js em Dev, no admin da VTEX

- src/css/servicos/servicos.css
> Kaizen - Renomeação de elemento

- _BackupCMS/Checkout/Default/checkout6-custom.js
> B2C-2000 - Aplicando em produção

- src/css/servicos/form-servicos.css
Ajustes no layout do formulário e Refatoração
> B2C-1948 - Ajustes no layout do formulário e Refatoração

- src/css/servicos/form-servicos.css
Ajuste do link preencha o formulário.
> B2C-1948 - Ajuste do link preencha o formulário.

- src/css/servicos/form-servicos.css
- src/css/servicos/servicos.css
> B2C-1948 - Refatoração.

- src/js/form-servicos.js
Inativando botão ancora do faça seu orcamento.
> B2C-1948 - Inativando botão ancora do faça seu orcamento.

- src/js/policies/checkout.js
Aplicando alterações em produção.
> B2C-1993 - Aplicando alterações em produção.

- arquivos/css/garantia.css
> B2C-2005 - Aplicando em produção.

- arquivos/css/servicos/form-servicos.css
- arquivos/css/servicos/servicos.css
- arquivos/js/form-servicos.js
> B2C-1948 - Aplicando em produção.

- arquivos/css/servicos/vantagens/pintura-automotiva.css
Vantagens - Aplicando em produção.
> B2C-1948 - Vantagens - Aplicando em produção.

- arquivos/css/servicos/servicos.css
> B2C-1948 - Vantagens - Fix em produção.

- arquivos/css/legacy/CSS.aut.far.product.css
> B2C-2006 - Aplicando em produção.

- src/js/policies/checkout.js
> B2C-2011 - Aplicando em produção

- src/js/checkout.js
Trocando Unidade NW10 para MG69
> B2C-2013 - Trocando Unidade NW10 para MG69

- src/css/transito-mais-livre.css
> B2C-2007 - Correção da URL do banner

- src/css/transito-mais-livre.css
Iniciar com o formulário oculto.
> B2C-2007 - Iniciar com o formulário oculto.

- src/js/transito-mais-livre.js
Inativa botão durante execução.
> B2C-2007 - Inativa botão durante execução.

- src/js/transito-mais-livre.js
Correção: Formato dos dados para requisição a API.
> B2C-2007 - Correção: Formato dos dados para requisição a API.

- src/js/transito-mais-livre.js
Correção: Validação de preenchimento.
> B2C-2007 - Correção: Validação de preenchimento.

- src/js/policies/checkout.js
> B2C-2013 - Aplicando em produção

- src/js/checkout.js
Trocando Unidade NW08 para MG68
> B2C-2047 - Trocando Unidade NW08 para MG68

- src/css/legacy/CSS.aut.far.search.css
> B2C-1953 - Importação de arquivo legado

- src/js/policies/checkout.js
> B2C-2047 - Aplicando em produção

- src/css/legacy/CSS.aut.far.system.css
Importando css do template sistema da QD
> B2C-1953 - Importando css do template sistema da QD

- src/css/smart-select.css
- src/js/smart-select.dev.js
> B2C-2061 - Modal de loading após seleção

- src/css/smart-select.css
Corrige z-index do modal na versão mobile
> B2C-2061 - Corrige z-index do modal na versão mobile

- arquivos/css/smart-select.css
- src/css/smart-select.css
Corrigindo a posição do modal na versão mobile.
> B2C-2061 - Corrigindo a posição do modal na versão mobile.

- src/css/servicos/servicos.css
- src/js/form-servicos.js
Modifica a estilização e adiciona o modal de formulário
> B2C-2009 - Modifica a estilização e adiciona o modal de formulário

- src/css/servicos/servicos.css
Conserta o posicionamento dos Banners
> B2C-2009 - Conserta o posicionamento dos Banners

- src/css/servicos/servicos.css
Conserta visualização do modal, possibilitando rolagem quando não couber na tela.
> B2C-2009 - Conserta visualizacao do modal

- src/js/policies/checkout.js
Ajusta troca de politicas comerciais de NW04 e MG67
> B2C-2065 - Ajusta troca de politicas comerciais de NW04 e MG67

- src/css/cep.component.css
Retira o botão "Usar minha localização" do checkout no ambiente de desenvolvimento.
> B2C-2068 - Retira o USAR MINHA LOCALIZACAO

- src/js/cep.component.js
Adiciona evento ao clique de OK no consulte o frete
> B2C-2068 - Adiciona evento ao clique de OK no consulte o frete

- src/js/cep.component.js
> B2C-2068 - Corrige evento de clique

- src/js/header.js
Passa as alteracoes feitas no header para dev
> B2C-2068 - Passa as alteracoes feitas no header para dev

- src/js/checkout.js
Altera fonte de logisticsInfo para o cookie do site
> B2C-2068 - Altera fonte de logisticsInfo para o cookie do site

- src/js/checkout.js
> B2C-2068 - Corrige funcao logisticsInfo

- src/js/cep.component.js
Retorna algumas funcoes que foram retiradas por engano
> B2C-2068 - Retorna algumas funcoes que foram retiradas por engano

- src/js/policies/header.js
Retira as alteracoes do header em producao
> B2C-2068 - Retira as alteracoes do header em producao

- src/js/legacy-MZ-CBKY.js
Remove evento de scroll top do botão de compra que aparece no mobile
> B2C-2089-Remove evento de scroll top do botão de compra

- src/js/topo.js
Adiciona condição para contemplar resposta visual no mobile
> Adiciona condição para contemplar resposta visual no mobile

- arquivos/js/legacy/legacy-MZ-CBKY.js
Foi corrigido o comportamento original de scroll do link no detalhe de produto
> B2C-2088  - Link sem direcionamento no detalhe do produto

- _BackupCMS/Checkout/Desenvolvimento/checkout6-custom.js
Altera função de trocar de canal e remover item do local storage para apenas remover canal do local storage (AG_SeletedChannel)
> B2C-2095 - Remove chamada de funcao para trocar de canal

- src/css/legacy/CSS.aut.far.product.css
- src/js/whatsapp-icon.js
Corrige erro que fazia com que evento fosse ignorado no GA
> Corrige chamada ao analytics no botão de WhatsApp no rodapé

- _BackupCMS/Checkout/Desenvolvimento/checkout6-custom.js
Cria um mutation observer para checar se o botão de instalação foi removido na página de checkout.
> B2C-2085 - Adiciona observer para checar se o botão foi removido

- _BackupCMS/Checkout/Desenvolvimento/checkout6-custom.js
O arquivo footer já continha o script importado, sendo necessário apenas no checkout.
> B2C-2317 - Adicionado código hubspot ao checkout e ao rodapé das páginas

- _BackupCMS/Checkout/Desenvolvimento/checkout6-custom.js
O código será refatorado à tarde.
> B2C-2352 - Altera funcionamento do CTA do checkout de acordo com scroll

- arquivos/css/topo.css
Reverts Autoglass-CDN/Autoglass-CDN.github.io#1562
> Revert "B2C - adiciona círculo nos itens das categorias e ajusta posição das setas"
